In [1]:
print("Hello World")

Hello World


In [6]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [9]:
from scipy import sparse

#Create a 2D Numpy array with a diagonal of ones, and zeros everywhere else

eye = np.eye(4)
print("NumPy array:\n{}".format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#Convert the NumPy array to a SciPy sparse matrix in CSR format
#Only the nonzero entries are stored

sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [18]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n{}".format(eye_coo))

COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [ ]:
%matplotlib

import matplotlib.pyplot as plt

#Generate a sequence of numbers from -10 do 10 with 100 steps in between
x = np.linspace(-10,10,100)
#Create a second array using sine
y = np.sin(x)

#The plot function makes a line chart of one array against another
plt.plot(x,y,marker="x")

In [1]:
import pandas as pd

#create a simple dataset of people
data = {"Name":["John", "Anna", "Peter", "Linda"],
       "Location":["New York", "Paris", "Berlin", "London"],
       "Age":[24,13,53,33]
       }

data_pandas = pd.DataFrame(data)
#IPython.display allows "Pretty printing" of dataframes in Jupyter Notebook

display(data_pandas)

Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

In [2]:
display(data_pandas[data_pandas.Age>30])

Name Location  Age
2  Peter   Berlin   53
3  Linda   London   33